//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Timer_Win32.rc
//
#define ID_BTN_OK                       1
#define IDC_MYICON                      2
#define IDD_TIMERWIN32_DIALOG           102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDS_TIMER_D_TITLE_EN            104
#define IDM_EXIT                        105
#define IDS_OUTPUT_EN                   105
#define IDS_OUTPUT_RU                   106
#define IDI_TIMERWIN32                  107
#define IDS_INPUT_EN                    107
#define IDI_SMALL                       108
#define IDS_INPUT_RU                    108
#define IDC_TIMERWIN32                  109
#define IDS_TIMER_D_TITLE_RU            110
#define IDS_TIMER_R_TITLE_EN            111
#define IDS_TIMER_R_TITLE_RU            112
#define IDS_DAY_EN                      113
#define IDS_HOUR_EN                     114
#define IDS_MINUTE_EN                   115
#define IDS_SECOND_EN                   116
#define IDS_DAY_RU                      117
#define IDS_HOUR_RU                     118
#define IDS_MINUTE_RU                   119
#define IDS_SECOND_RU                   120
#define IDS_START_EN                    121
#define IDS_START_RU                    122
#define IDS_STOP_EN                     123
#define IDS_PAUSE_EN                    124
#define IDS_CONTINUE_EN                 125
#define IDS_STOP_RU                     126
#define IDS_PAUSE_RU                    127
#define IDR_MAINFRAME                   128
#define IDS_CONTINUE_RU                 128
#define IDS_CHANGELANG_EN               129
#define IDS_CHANGELANG_TITLE_EN         130
#define IDS_CHANGELANG_RU               131
#define IDS_CHANGELANG_TITLE_RU         132
#define IDS_CHANGELANG_TEXT_EN          133
#define IDS_CHANGELANG_TEXT_RU          134
#define IDS_RESET_EN                    135
#define IDD_START                       136
#define IDD_DEFAULT_TIMER               136
#define IDS_RESET_RU                    136
#define IDD_REVERSE_TIMER               137
#define IDS_DAY_OF_WEEK_EN              137
#define IDS_DAY_OF_WEEK_RU              138
#define IDD_SYSTEM_TIMER                139
#define IDS_MONTH_EN                    139
#define IDD_STOPWATCH                   140
#define IDS_MONTH_RU                    140
#define IDD_CLOCK_MODERN                141
#define IDS_YEAR_EN                     141
#define IDS_YEAR_RU                     142
#define IDD_DIALOG1                     143
#define IDD_CLOCK_OLD                   143
#define IDS_MENU_FILE_EN                143
#define IDD_DIALOG2                     144
#define IDS_MENU_FILE_RU                144
#define IDS_MENU_HELP_EN                145
#define IDS_MENU_HELP_RU                146
#define IDS_NO_INPUT_EN                 147
#define IDS_NO_INPUT_RU                 148
#define IDD_CHANGE_LANGUAGE             148
#define IDS_TITLE_ERROR_EN              149
#define IDD_ADD_EVENT                   149
#define IDS_TITLE_ERROR_RU              150
#define IDS_END_TIMER_EN                151
#define IDD_CHOOSE_DAY                  151
#define IDS_END_TIMER_RU                152
#define IDS_TITLE_TIMER_EN              153
#define IDS_TITLE_TIMER_RU              154
#define IDS_INVALID_INPUT_EN            155
#define IDS_INVALID_INPUT_RU            156
#define IDS_MENU_LANGUAGE_EN            157
#define IDS_MENU_LANGUAGE_RU            158
#define IDS_MENU_TIMER_EN               159
#define IDS_MENU_TIMER_RU               160
#define IDS_MENU_CLOCK_EN               161
#define IDS_MENU_CLOCK_RU               162
#define IDS_SUBMENU_EXIT_EN             163
#define IDS_SUBMENU_EXIT_RU             164
#define IDS_SUBMENU_ABOUT_EN            165
#define IDS_SUBMENU_ABOUT_RU            166
#define IDS_SUBMENU_LANGUAGE_RU         167
#define IDS_SUBMENU_LANGUAGE_EN         168
#define IDS_SUBMENU_TIMER_DEFAULT_EN    169
#define IDS_SUBMENU_TIMER_DEFAULT_RU    170
#define IDS_SUBMENU_TIMER_REVERSE_EN    171
#define IDS_SUBMENU_TIMER_REVERSE_RU    172
#define IDS_SUBMENU_TIMER_SD_EN         173
#define IDS_SUBMENU_TIMER_SD_RU         174
#define IDS_SUBMENU_STOPWATCH_EN        175
#define IDS_SUBMENU_STOPWATCH_RU        176
#define IDS_SUBMENU_CLOCK_MODERN_EN     177
#define IDS_SUBMENU_CLOCK_RU            178
#define IDS_SUBMENU_CLOCK_MODERN_RU     178
#define IDS_SUBMENU_CLOCK_OLD_EN        179
#define IDS_SUBMENU_CLOCK_OLD_RU        180
#define IDS_SUBMENU_EVENT_SAVE_EN       181
#define IDS_SUBMENU_EVENT_SAVE_RU       182
#define IDS_SUBMENU_EVENT_LOAD_EN       183
#define IDS_SUBMENU_EVENT_LOAD_RU       184
#define IDS_SUBMENU_EVENT_ADD_EN        185
#define IDS_SUBMENU_EVENT_ADD_RU        186
#define IDS_SUBMENU_EVENT_DELETE_EN     187
#define IDS_SUBMENU_EVENT_DELETE_RU     188
#define IDS_MENU_EVENT_EN               189
#define IDS_MENU_EVENT_RU               190
#define IDC_START                       1002
#define IDC_STOP                        1003
#define IDC_RESET                       1004
#define IDC_PAUSE                       1004
#define IDC_EDIT_MINUTE                 1007
#define IDC_EDIT_HOUR1                  1008
#define IDC_EDIT_SECOND                 1009
#define IDC_R_START                     1010
#define IDC_R_STOP                      1011
#define IDC_R_PAUSE                     1012
#define IDC_EDIT_R_HOUR1                1013
#define IDC_EDIT_R_MINUTE               1014
#define IDC_EDIT_R_SECOND               1015
#define IDC_TEXT_INPUT                  1016
#define IDC_R_CONTINUE                  1017
#define IDC_TEXT_OUTPUT                 1018
#define IDC_EDIT_R_MINUTE_INPUT         1019
#define IDC_EDIT_R_HOUR_INPUT           1020
#define IDC_EDIT_R_SECOND_INPUT         1021
#define IDC_CONTINUE                    1022
#define IDC_EDIT_HOUR_INPUT             1023
#define IDC_EDIT_MINUTE_INPUT           1024
#define IDC_EDIT_SECOND_INPUT           1025
#define IDC_EDIT_DAY_INPUT              1026
#define IDC_EDIT_SW_HOUR                1027
#define IDC_EDIT_SW_MINUTE              1028
#define IDC_EDIT_SW_SECOND              1029
#define IDC_SW_START                    1030
#define IDC_EDIT_DAY                    1030
#define IDC_SW_STOP                     1031
#define IDC_SW_PAUSE                    1032
#define IDC_SW_CONTINUE                 1033
#define IDC_EDIT_SW_MINUTE2             1034
#define IDC_EDIT_SW_MSECOND             1036
#define IDC_EDIT_CLOCK_HOUR             1037
#define IDC_EDIT_CLOCK_MINUTE           1038
#define IDC_EDIT_CLOCK_SECOND           1039
#define IDC_S_START                     1042
#define IDC_EDIT_CLOCK_DAY              1043
#define IDC_S_RESET                     1043
#define IDC_EDIT_CLOCK_MOUNTH           1044
#define IDC_EDIT_CLOCK_MONTH            1044
#define IDC_EDIT_CLOCK_YEAR             1045
#define IDC_EDIT_CLOCK_O_DAY            1045
#define IDC_EDIT_CLOCK_DAYOFWEEK        1046
#define IDC_EDIT_CLOCK_O_MONTH          1046
#define IDC_CHOICE_EN                   1046
#define IDC_EDIT_CLOCK_O_YEAR           1047
#define IDC_CHOICE_RU                   1047
#define IDC_OUTPUT                      1048
#define IDC_TEXT_HOUR                   1049
#define IDC_TEXT_MINUTE                 1050
#define IDC_EDIT_CLOCK_O_DAYOFWEEK      1051
#define IDC_TEXT_SECOND                 1051
#define IDC_TEXT_DAY                    1052
#define IDC_TEXT_DAY_OF_WEEK            1053
#define IDC_TEXT_MONTH                  1055
#define IDC_TEXT_YEAR                   1056
#define IDC_SECOND                      1059
#define ID_BTN_ADD                      1060
#define IDC_EDIT_DESC                   1061
#define IDC_EDIT_HOURS_BEGIN            1063
#define IDC_EDIT_MINUTES_BEGIN          1064
#define IDC_EDIT_HOURS_END              1065
#define IDC_EDIT_MINUTES_END            1066
#define IDC_CHOOSE_DAY                  1071
#define IDOK                            1072
#define IDC_ON_MONDAY                   1074
#define IDC_ON_MONDAY2                  1075
#define IDC_ON_TUESDAY                  1075
#define IDC_ON_MONDAY3                  1076
#define IDC_ON_WEDNESDAY                1076
#define IDC_LIST1                       1076
#define IDC_ON_MONDAY4                  1077
#define IDC_ON_THURSDAY                 1077
#define IDC_COMBO2                      1077
#define IDC_ON_MONDAY5                  1078
#define IDC_ON_FRIDAY                   1078
#define IDC_ON_MONDAY6                  1079
#define IDC_ON_SATURDAY                 1079
#define IDC_ON_MONDAY7                  1080
#define IDC_ON_SUNDAY                   1080
#define ID_TIMER_HOURS                  32771
#define ID_TIMER_MINUTES                32772
#define ID_TIMER_SECONDS                32773
#define ID_STARTTIMER_START             32774
#define ID_TIMER_START                  32775
#define ID_TIMER_REVERSETIMER           32776
#define ID_TIMER_SYSTEM                 32777
#define ID_TIMER_STOPWATCH              32778
#define ID_TIMER_DEFAULT                32779
#define ID_CLOCK_MODERN                 32780
#define ID_CLOCK_OLD                    32781
#define ID_LANGUAGE_CHOOSELANGUAGE      32782
#define ID_LANGUAGE                     32783
#define ID_LANGUAGE_CHOOSELANGUAGE32784 32784
#define ID_PLAN_ADDNEWEVENT             32785
#define ID_EVENTS_DELETEEVENT           32786
#define ID_PLAN_ADD                     32787
#define ID_EVENTS_ADD                   32788
#define ID_EVENTS_DELETE                32789
#define ID_EVENTS_SAVECURRENTEVENTS     32790
#define ID_EVENTS_SAVE                  32791
#define ID_EVENTS_LOADEVENTSFROMSAVE    32792
#define ID_EVENTS_LOAD                  32793
#define ID_HELP_CHOOSELANGUAGE          32794
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32795
#define _APS_NEXT_CONTROL_VALUE         1078
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
